### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by WolfgangFahl** [vinodpandey/python-port-forward#2]
git clone https://github.com/vinodpandey/python-port-forward

works. The described procedure does not

**Comment by vinodpandey** [comment]
We have updated README with more details on executing the python file. Please let us know if you are receiving any error which can help us in debugging the issue.

Also, please answer below question to help in debugging this issue further.
1. OS and python version.
2. Is the default 80>8080 port forward working for you?

**Comment by WolfgangFahl** [comment]
thanks for fixing this
IMHO the installation procedure has nothing todo with OS procedure or python version - it was just and invalid git link.
I don't have any functional problems - thank you.
