### ISSUE TITLE
What library does the file() function need?

### ISSUE THREAD

**Issue by saelozahra** [vinodpandey/python-port-forward#6]
hello dears ❤️💕

I wanted to use this script, but I was facing this error: that the file() function does not belong to any of the libraries

![image](https://github.com/vinodpandey/python-port-forward/assets/6209081/68ad3bc2-f527-4097-b44e-14800104bd6c)

**Is it possible to guide me how to install the prerequisites of this script?**

**Comment by vinodpandey** [comment]
Thanks for pointing out this issue. The above code was for Python 2.7 version. I have just upgraded the code to Python 3 since Python 2 has already reached end-of-life on January 1, 2020. You can checkout the latest code from repository and that should work fine with any Python 3.x version now.
